### ISSUE TITLE
老哥这个项目还会更新么

### ISSUE THREAD

**Issue by king-bcolor** [SilentFlute/umi4-admin#2]

**Comment by SilentFlute** [comment]
你可以先用用看哈, 我个人觉得这个管理后台的框架已经比较完善了, 克隆下来根据自己的业务微调一下应该就可以用了, 毕竟大的框架基本都差不多

**Comment by king-bcolor** [comment]
> 你可以先用用看哈, 我个人觉得这个管理后台的框架已经比较完善了, 克隆下来根据自己的业务微调一下应该就可以用了, 毕竟大的框架基本都差不多

ok thank
