### ISSUE TITLE
好兄弟4.2了快更新，支持你✊

### ISSUE THREAD

**Issue by WyntersN** [SilentFlute/umi4-admin#3]

**Comment by SilentFlute** [comment]
哈哈哈, 4.2有什么特别的更新吗?

**Comment by WyntersN** [comment]
图表 变成了 2.0了

**Comment by SilentFlute** [comment]
什么图表啊? 图表相关的解决方案可以自行安装集成使用

**Comment by WyntersN** [comment]
ant-design/charts 不好用，想用 echarts 又配置不来

**Comment by WyntersN** [comment]
我还发现 

   layout: {
      title: '---',
      logo: '/images/logo.png',
    },

logo 改不了

**Comment by SilentFlute** [comment]
你去[echarts官网](https://echarts.apache.org/)看看如何使用, 引入之后在`react`相应的生命周期里使用就行.
或者你找找看有没有用户封装的第三方的`react`版本的`echarts`.
我这个项目就是提供一个框架, 里面不同的解决方案就自己集成了. 因为大的框架是一样的, 但每个人需求不同, 于是具体的细节的解决方案就因人而异了, 就需要用户自己来处理了
